apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app
  prune: true
  wait: true
  timeout: 5m
