apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  components:
    - ../../app/patch/prod